### ISSUE TITLE
log errors

### ISSUE THREAD

**Issue by jacobabiola** [hummingbot/deploy-examples#28]
Hello i get this error message every time i start hummingBot from the terminal 

`2023-07-14 11:45:02,441 - 1 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - The Kraken API does not allow enough bandwidth for a reduced rate-limit share percentage. Current percentage: 50.0.
2023-07-14 11:45:03,478 - 1 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/time. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: oQAbPJHBHUvxMTvKNmBnL-FILgj26zILR1tToXWNz3utxgIuh4o03Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 11:45:03,481 - 1 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2023-07-14 11:45:03,807 - 1 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1092, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1105, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 896, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/exchangeInfo. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: h2M4yjeYd4lbQFsg6fsRXi-vsPI22kbt4V25gpBxCPAWjpm3PLyv7A==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 11:45:12,740 - 1 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/trading_pair_fetcher.py", line 64, in call_fetch_pairs
    pairs = await fetch_fn
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_exchange.py", line 867, in all_trading_pairs
    return await K2APIOrderBookDataSource.fetch_trading_pairs()
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_api_order_book_data_source.py", line 62, in fetch_trading_pairs
    async with client.get(f"{constants.REST_URL}{constants.GET_TRADING_PAIRS}",
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2023-07-14 11:53:35,919 - 1 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - The Kraken API does not allow enough bandwidth for a reduced rate-limit share percentage. Current percentage: 50.0.
2023-07-14 11:53:37,106 - 1 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/time. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: _vnLx378MRrEeGhznQtQh9MNZhScLdohUxQFYLnOEkLHxEBRLVon3w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 11:53:37,111 - 1 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2023-07-14 11:53:37,362 - 1 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1092, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1105, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 896, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/exchangeInfo. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 6fcabznh5eXQrZ-nTZK-EA88i-wImF-aVdQxWxpVqHvwtCpno-jHDw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 11:53:46,732 - 1 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/trading_pair_fetcher.py", line 64, in call_fetch_pairs
    pairs = await fetch_fn
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_exchange.py", line 867, in all_trading_pairs
    return await K2APIOrderBookDataSource.fetch_trading_pairs()
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_api_order_book_data_source.py", line 62, in fetch_trading_pairs
    async with client.get(f"{constants.REST_URL}{constants.GET_TRADING_PAIRS}",
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2023-07-14 12:04:18,436 - 1 - hummingbot.connector.exchange.kraken.kraken_exchange - WARNING - The Kraken API does not allow enough bandwidth for a reduced rate-limit share percentage. Current percentage: 50.0.
2023-07-14 12:04:19,408 - 1 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/time. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: ivR4rK6jL2Yl-5vhw0Cq3uPx36F2Stl95NguXIUvJVjn4jhB5anQdQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 12:04:19,410 - 1 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2023-07-14 12:04:19,653 - 1 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1092, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1105, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 896, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.us/api/v3/exchangeInfo. HTTP status is 403. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: M55f_-gpwT5vZvq0hOYRNmGvx5bag5KzMrq05_xEYATLWkqFfdwLcQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2023-07-14 12:04:28,763 - 1 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/trading_pair_fetcher.py", line 64, in call_fetch_pairs
    pairs = await fetch_fn
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_exchange.py", line 867, in all_trading_pairs
    return await K2APIOrderBookDataSource.fetch_trading_pairs()
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_api_order_book_data_source.py", line 62, in fetch_trading_pairs
    async with client.get(f"{constants.REST_URL}{constants.GET_TRADING_PAIRS}",
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
`

**Comment by rapcmia** [comment]
Hi @jacobabiola thanks for opening the ticket, however the error indicates that `The Amazon CloudFront distribution is configured to block access from your country..` might be an issue with your server. Also can you at least let us know how this happened or steps to reproduce? I am not getting this error atm. Thanks

**Comment by jacobabiola** [comment]
@rapcmia i am running Hummingbot on a desktop docker setup. i don't know how that might be the issue

**Comment by nikspz** [comment]
hi @jacobabiola this is expected behavior since it's not related to the bot Client, it's related to your location (from not supported by Cloudfront warning message). 
If you want to fix You could try to use Cloud services such as AWS. 
Using different locations of the Cloud services could fix this issue.

![image](https://github.com/hummingbot/deploy-examples/assets/83953535/e6420953-cee5-49ac-933d-47ed122d1be7)
Also this issue might not affect to use other connectors locally. So you could try to run them.
